# Generated by Django 5.2.17 on 2026-10-03 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon', models.CharField(blank=True, max_length=16, verbose_name='гость (случайный номер из куки)')),
                ('day', models.DateField(db_index=True)),
                ('section', models.CharField(db_index=True, max_length=24)),
                ('platform', models.CharField(default='web', max_length=3)),
                ('opens', models.PositiveIntegerField(default=0)),
                ('seconds', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'использование раздела за день',
                'verbose_name_plural': 'использование разделов',
                'indexes': [models.Index(fields=['day', 'section'], name='metrics_use_day_19c621_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'anon', 'day', 'section', 'platform'), name='one_use_row')],
            },
        ),
    ]
