# Generated by Django 5.2.17 on 2026-09-18 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='название')),
                ('city', models.CharField(max_length=80, verbose_name='город')),
                ('address', models.CharField(blank=True, max_length=240, verbose_name='адрес')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='широта')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='долгота')),
                ('phone', models.CharField(blank=True, max_length=60, verbose_name='телефон')),
                ('url', models.URLField(blank=True, verbose_name='сайт/соцсеть')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='places/', verbose_name='фото')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Опубликован'), ('rejected', 'Отклонён')], default='pending', max_length=10, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='добавлено')),
                ('category', models.CharField(choices=[('gp', 'Терапевт / семейный'), ('cardio', 'Кардиолог'), ('neuro', 'Невролог'), ('pediatr', 'Педиатр'), ('dentist', 'Стоматолог'), ('gyneco', 'Гинеколог'), ('psych', 'Психолог / психотерапевт'), ('other', 'Другое')], max_length=30, verbose_name='специализация')),
                ('experience', models.PositiveSmallIntegerField(default=0, verbose_name='опыт, лет')),
                ('clinic', models.CharField(blank=True, max_length=160, verbose_name='клиника/кабинет')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='кто добавил')),
            ],
            options={
                'verbose_name': 'врач',
                'verbose_name_plural': 'врачи',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
