# Generated by Django 5.2.17 on 2026-09-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='platform_verified',
            field=models.BooleanField(default=False, help_text='Ставит админ после проверки документов/контактов', verbose_name='проверено платформой'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='category',
            field=models.CharField(choices=[('gp', 'Терапевт / семейный'), ('cardio', 'Кардиолог'), ('neuro', 'Невролог'), ('pediatr', 'Педиатр'), ('dentist', 'Стоматолог'), ('gyneco', 'Гинеколог'), ('psych', 'Психолог / психотерапевт'), ('hijama', 'Хиджама'), ('other', 'Другое')], max_length=30, verbose_name='специализация'),
        ),
    ]
