# Generated by Django 5.2.17 on 2026-09-18 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('country_from', models.CharField(max_length=60, verbose_name='откуда')),
                ('country_to', models.CharField(max_length=60, verbose_name='куда')),
                ('body', models.TextField(verbose_name='история')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Опубликован'), ('rejected', 'Отклонён')], default='pending', max_length=10, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'история переезда',
                'verbose_name_plural': 'истории переездов',
                'ordering': ['-created_at'],
            },
        ),
    ]
