# Generated by Django 5.2.17 on 2026-09-18 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_seed_themes_and_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('nickname', 'Ник'), ('city', 'Город'), ('first_name', 'Имя')], max_length=20, unique=True, verbose_name='поле')),
                ('label', models.CharField(max_length=60, verbose_name='подпись')),
                ('required', models.BooleanField(default=False, verbose_name='обязательное')),
                ('enabled', models.BooleanField(default=True, verbose_name='спрашивать при регистрации')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'поле регистрации',
                'verbose_name_plural': 'поля регистрации',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=80, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=40, verbose_name='ник'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Участник'), ('support', 'Поддержка'), ('admin', 'Админ'), ('super_admin', 'Супер-админ')], default='user', max_length=12, verbose_name='роль'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.theme', verbose_name='тема оформления'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120, verbose_name='действие')),
                ('target', models.CharField(blank=True, max_length=200, verbose_name='объект')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='когда')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='кто')),
            ],
            options={
                'verbose_name': 'запись журнала',
                'verbose_name_plural': 'журнал действий',
                'ordering': ['-created_at'],
            },
        ),
    ]
