# Generated by Django 5.2.17 on 2026-09-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seed_registration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform_verified',
            field=models.BooleanField(default=False, help_text='Продавец/исполнитель/заведение проверены админом (документы, контакты)', verbose_name='проверен платформой'),
        ),
    ]
