# Generated by Django 5.2.17 on 2026-09-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_platform_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='findable_by_phone',
            field=models.BooleanField(default=False, help_text='Друзья, у которых ваш номер в контактах, увидят, что вы на ilm4', verbose_name='меня можно найти по номеру'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='телефон'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_key',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='ключ номера (хеш последних 9 цифр)'),
        ),
    ]
