# Generated by Django 5.2.17 on 2026-09-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_phone_discovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='Заполняется при входе из Telegram (мини-приложение)', null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=64, verbose_name='Telegram @'),
        ),
    ]
