# Generated by Django 5.2.17 on 2026-09-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_reports_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, help_text='Уведомления и сообщения бота приходят на этом языке', max_length=8, verbose_name='язык интерфейса'),
        ),
    ]
