# Generated by Django 5.2.17 on 2026-09-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, help_text='Когда номер подтверждён через Telegram (кнопка «Отправить мой номер»). Один номер — один аккаунт: так боты не плодят объявления и анкеты', null=True, verbose_name='номер подтверждён'),
        ),
    ]
