# Generated by Django 5.2.17 on 2026-09-30 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_phone_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('phone', 'номер телефона'), ('telegram', 'Telegram-аккаунт')], max_length=10, verbose_name='что')),
                ('key', models.CharField(db_index=True, max_length=64, verbose_name='отпечаток')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='когда')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='кто заблокировал')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans', to=settings.AUTH_USER_MODEL, verbose_name='аккаунт')),
            ],
            options={
                'verbose_name': 'чёрный список',
                'verbose_name_plural': 'чёрный список (номера и Telegram)',
                'constraints': [models.UniqueConstraint(fields=('kind', 'key'), name='one_ban_per_identity')],
            },
        ),
    ]
