# Generated by Django 5.2.17 on 2026-10-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_banned_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, help_text='В ней показываем «≈» рядом с ценами. Пусто — определяем сами: по стране или номеру', max_length=3, verbose_name='валюта для цен'),
        ),
    ]
