# Generated by Django 5.2.17 on 2026-10-02 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def findable_default(apps, schema_editor):
    """Сайт ещё не запущен: у тестовых аккаунтов «найти по номеру» включаем, как у новых."""
    apps.get_model('accounts', 'User').objects.filter(findable_by_phone=False).update(findable_by_phone=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=160, verbose_name='о себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='handle',
            field=models.CharField(blank=True, help_text='По нему вас находят в поиске. Латинские буквы, цифры и «_»', max_length=32, null=True, unique=True, verbose_name='имя пользователя (@имя)'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='был(а) в сети'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_privacy',
            field=models.CharField(choices=[('all', 'Все'), ('close', 'Близкие друзья'), ('nobody', 'Никто')], default='nobody', max_length=6, verbose_name='кто видит мой номер'),
        ),
        migrations.AddField(
            model_name='user',
            name='seen_privacy',
            field=models.CharField(choices=[('all', 'Все'), ('close', 'Близкие друзья'), ('nobody', 'Никто')], default='all', max_length=6, verbose_name='кто видит, когда я в сети'),
        ),
        migrations.AlterField(
            model_name='user',
            name='findable_by_phone',
            field=models.BooleanField(default=True, help_text='Кто знает ваш номер, найдёт вас в поиске чатов. Сам номер при этом не показывается', verbose_name='меня можно найти по номеру'),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('x', 'X (Twitter)'), ('vk', 'VK'), ('github', 'GitHub'), ('discord', 'Discord'), ('linkedin', 'LinkedIn'), ('website', 'Сайт'), ('other', 'Другое')], max_length=12, verbose_name='сеть')),
                ('value', models.CharField(max_length=120, verbose_name='имя или ссылка')),
                ('privacy', models.CharField(choices=[('all', 'Все'), ('close', 'Близкие друзья'), ('nobody', 'Никто')], default='all', max_length=6, verbose_name='кто видит')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ссылка на соцсеть',
                'verbose_name_plural': 'ссылки на соцсети',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CloseFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_of', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_friends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'близкий друг',
                'verbose_name_plural': 'близкие друзья',
                'constraints': [models.UniqueConstraint(fields=('owner', 'friend'), name='one_close_friend')],
            },
        ),
        migrations.RunPython(findable_default, migrations.RunPython.noop),
    ]
