# Generated by Django 5.2.17 on 2026-10-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_people_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ui',
            field=models.JSONField(blank=True, default=dict, verbose_name='настройки интерфейса'),
        ),
    ]
