# Generated by Django 5.2.17 on 2026-10-02 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_ui'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='день рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='forward_privacy',
            field=models.CharField(choices=[('all', 'Все'), ('close', 'Близкие друзья'), ('nobody', 'Никто')], default='all', max_length=6, verbose_name='кто может ссылаться на мой профиль при пересылке'),
        ),
        migrations.AddField(
            model_name='user',
            name='invite_privacy',
            field=models.CharField(choices=[('all', 'Все'), ('close', 'Близкие друзья'), ('nobody', 'Никто')], default='all', max_length=6, verbose_name='кто может добавлять меня в группы'),
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='avatars/', verbose_name='фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'фото профиля',
                'verbose_name_plural': 'фото профиля',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
