# Generated by Django 5.2.17 on 2026-10-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_telegram_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='counts_privacy',
            field=models.CharField(choices=[('all', 'Все'), ('close', 'Близкие друзья'), ('nobody', 'Никто')], default='all', max_length=6, verbose_name='кто видит мои счётчики (записи, подписчики, подписки)'),
        ),
    ]
