# Generated by Django 5.2.17 on 2026-10-03 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('auth_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'запомненный вход (несколько аккаунтов)',
                'verbose_name_plural': 'запомненные входы (несколько аккаунтов)',
            },
        ),
    ]
