# Generated by Django 5.2.17 on 2026-10-03 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_device_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Записи и сторис видят только подписчики, которых человек одобрил.', verbose_name='закрытый профиль'),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('board', 'Объявления, работа, услуги'), ('spaces', 'Сообщества')], max_length=10, verbose_name='раздел')),
                ('name', models.CharField(max_length=40, verbose_name='имя в разделе')),
                ('avatar', models.ImageField(blank=True, upload_to='personas/', verbose_name='аватар в разделе')),
                ('link_main', models.BooleanField(default=True, verbose_name='показывать ссылку на основной профиль')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль раздела (маска)',
                'verbose_name_plural': 'профили разделов (маски)',
                'constraints': [models.UniqueConstraint(fields=('user', 'section'), name='one_persona_per_section')],
            },
        ),
    ]
