# Generated by Django 5.2.17 on 2026-10-03 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_personas_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ua', models.CharField(blank=True, max_length=300, verbose_name='браузер')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='вход')),
                ('last_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='был активен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'сеанс сайта',
                'verbose_name_plural': 'сеансы сайта',
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
