# Generated by Django 5.2.17 on 2026-09-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_rename_map_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halalplace',
            name='category',
            field=models.CharField(choices=[('mosque', 'Мечеть'), ('cafe', 'Кафе / ресторан'), ('shop', 'Магазин продуктов'), ('hotel', 'Отель'), ('butcher', 'Мясная лавка'), ('other', 'Другое')], max_length=30, verbose_name='категория'),
        ),
    ]
