# Generated by Django 5.2.17 on 2026-09-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_mosque_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='halalplace',
            name='platform_verified',
            field=models.BooleanField(default=False, help_text='Ставит админ после проверки документов/контактов', verbose_name='проверено платформой'),
        ),
    ]
