# Generated by Django 5.2.17 on 2026-09-23 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_platform_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='halalplace',
            name='accessible',
            field=models.BooleanField(default=False, verbose_name='доступно для колясок'),
        ),
        migrations.AddField(
            model_name='halalplace',
            name='affiliation',
            field=models.CharField(blank=True, help_text='Например: Управление мусульман Узбекистана, округ / частная', max_length=200, verbose_name='кому принадлежит'),
        ),
        migrations.AddField(
            model_name='halalplace',
            name='branch',
            field=models.CharField(blank=True, choices=[('sunni', 'Суннитская'), ('shia', 'Шиитская'), ('other', 'Другое')], max_length=8, verbose_name='течение'),
        ),
        migrations.AddField(
            model_name='halalplace',
            name='has_jumua',
            field=models.BooleanField(default=False, verbose_name='джума-намаз'),
        ),
        migrations.AddField(
            model_name='halalplace',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='парковка'),
        ),
        migrations.AddField(
            model_name='halalplace',
            name='has_women',
            field=models.BooleanField(default=False, verbose_name='женский зал'),
        ),
        migrations.AddField(
            model_name='halalplace',
            name='has_wudu',
            field=models.BooleanField(default=False, verbose_name='место для омовения'),
        ),
        migrations.AddField(
            model_name='halalplace',
            name='imam',
            field=models.CharField(blank=True, max_length=120, verbose_name='имам'),
        ),
        migrations.AddField(
            model_name='halalplace',
            name='khutba_lang',
            field=models.CharField(blank=True, max_length=80, verbose_name='язык хутбы'),
        ),
        migrations.AddField(
            model_name='halalplace',
            name='madhhab',
            field=models.CharField(blank=True, choices=[('hanafi', 'Ханафитский'), ('shafii', 'Шафиитский'), ('maliki', 'Маликитский'), ('hanbali', 'Ханбалитский'), ('jafari', 'Джафаритский'), ('mixed', 'Разные мазхабы')], max_length=8, verbose_name='мазхаб'),
        ),
        migrations.CreateModel(
            name='PlaceConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=True, verbose_name='информация верна')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='что неточно')),
                ('resolved', models.BooleanField(default=False, verbose_name='разобрано модератором')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='когда')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='maps.halalplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'подтверждение / уточнение',
                'verbose_name_plural': 'подтверждения и уточнения мест',
                'constraints': [models.UniqueConstraint(fields=('place', 'user'), name='one_confirmation_per_user')],
            },
        ),
    ]
