# Generated by Django 5.2.17 on 2026-09-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_mosque_info_confirmations'),
    ]

    operations = [
        migrations.AddField(
            model_name='halalplace',
            name='kind',
            field=models.CharField(blank=True, choices=[('official', 'Официальная (муфтият / духовное управление)'), ('community', 'Общинная / частная'), ('foundation', 'Фонд / организация'), ('other', 'Другое')], max_length=10, verbose_name='на чём держится'),
        ),
        migrations.AddField(
            model_name='halalplace',
            name='manhaj',
            field=models.CharField(blank=True, choices=[('sunna', 'Ахлю-с-Сунна (без уточнения)'), ('ashari', 'Ашариты / матуридиты'), ('athari', 'Асариты / саляфиты'), ('sufi', 'Суфийская (тарикат)'), ('tabligh', 'Таблиг'), ('other', 'Другое')], help_text='Примерно, по словам прихожан. Уточняется подтверждениями', max_length=8, verbose_name='манхадж / направление'),
        ),
        migrations.AddField(
            model_name='placeconfirmation',
            name='suggested_branch',
            field=models.CharField(blank=True, choices=[('sunni', 'Суннитская'), ('shia', 'Шиитская'), ('other', 'Другое')], max_length=8, verbose_name='предлагают: течение'),
        ),
        migrations.AddField(
            model_name='placeconfirmation',
            name='suggested_kind',
            field=models.CharField(blank=True, choices=[('official', 'Официальная (муфтият / духовное управление)'), ('community', 'Общинная / частная'), ('foundation', 'Фонд / организация'), ('other', 'Другое')], max_length=10, verbose_name='предлагают: на чём держится'),
        ),
        migrations.AddField(
            model_name='placeconfirmation',
            name='suggested_madhhab',
            field=models.CharField(blank=True, choices=[('hanafi', 'Ханафитский'), ('shafii', 'Шафиитский'), ('maliki', 'Маликитский'), ('hanbali', 'Ханбалитский'), ('jafari', 'Джафаритский'), ('mixed', 'Разные мазхабы')], max_length=8, verbose_name='предлагают: мазхаб'),
        ),
        migrations.AddField(
            model_name='placeconfirmation',
            name='suggested_manhaj',
            field=models.CharField(blank=True, choices=[('sunna', 'Ахлю-с-Сунна (без уточнения)'), ('ashari', 'Ашариты / матуридиты'), ('athari', 'Асариты / саляфиты'), ('sufi', 'Суфийская (тарикат)'), ('tabligh', 'Таблиг'), ('other', 'Другое')], max_length=8, verbose_name='предлагают: манхадж'),
        ),
    ]
