# Generated by Django 5.2.17 on 2026-09-18 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_enable_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='слаг')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='кратко')),
                ('body', models.TextField(verbose_name='текст')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/', verbose_name='обложка')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='закреплена')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
