# Generated by Django 5.2.17 on 2026-09-24 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='устройство')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='выдан')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='последний раз')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'вход в приложении',
                'verbose_name_plural': 'входы в приложении',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, unique=True, verbose_name='push-токен')),
                ('platform', models.CharField(blank=True, max_length=10, verbose_name='платформа')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'телефон для пушей',
                'verbose_name_plural': 'телефоны для пушей',
            },
        ),
    ]
