# Generated by Django 5.2.17 on 2026-09-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_vacancy_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='kind',
            field=models.CharField(choices=[('vacancy', 'Вакансия — ищу работника'), ('resume', 'Резюме — ищу работу')], db_index=True, default='vacancy', max_length=8, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.CharField(blank=True, help_text='Для вакансии. В резюме можно оставить пустым', max_length=160, verbose_name='компания'),
        ),
    ]
