# Generated by Django 5.2.17 on 2026-09-18 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='название')),
                ('kind', models.CharField(choices=[('translate', 'Переводы документов (нотариальные)'), ('lawyer', 'Исламский юрист / консультация'), ('tour', 'Туры: хадж и умра'), ('other', 'Другая услуга')], max_length=12, verbose_name='вид')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='город')),
                ('description', models.TextField(verbose_name='описание')),
                ('price_text', models.CharField(blank=True, max_length=120, verbose_name='цена (текстом)')),
                ('contact', models.CharField(max_length=120, verbose_name='контакт')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Опубликован'), ('rejected', 'Отклонён')], default='pending', max_length=10, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
                'ordering': ['-created_at'],
            },
        ),
    ]
