# Generated by Django 5.2.17 on 2026-10-02 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='название')),
                ('emoji', models.CharField(default='🤝', max_length=8, verbose_name='значок')),
                ('compete', models.BooleanField(default=False, help_text='Таблица: кто сколько выполнил. Выключено — просто общий список', verbose_name='соревнование')),
                ('invite_code', models.CharField(max_length=24, unique=True, verbose_name='код приглашения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_boards_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'общий трекер',
                'verbose_name_plural': 'общие трекеры',
            },
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tracker.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'участник общего трекера',
                'verbose_name_plural': 'участники общих трекеров',
            },
        ),
        migrations.AddField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(related_name='tracker_boards', through='tracker.BoardMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='что делать')),
                ('emoji', models.CharField(default='✅', max_length=8, verbose_name='значок')),
                ('color', models.CharField(default='#6d5efc', max_length=7, verbose_name='цвет')),
                ('kind', models.CharField(choices=[('check', 'Сделал / не сделал'), ('count', 'Количество (стаканы, страницы, минуты)')], default='check', max_length=5, verbose_name='вид')),
                ('target', models.PositiveIntegerField(default=1, verbose_name='цель в день')),
                ('unit', models.CharField(blank=True, max_length=16, verbose_name='единица (стаканов, страниц…)')),
                ('days', models.CharField(default='1234567', help_text='1 — понедельник … 7 — воскресенье', max_length=7, verbose_name='дни недели')),
                ('once_on', models.DateField(blank=True, null=True, verbose_name='разовое дело — на этот день')),
                ('remind_at', models.TimeField(blank=True, null=True, verbose_name='напомнить в')),
                ('tz_offset', models.SmallIntegerField(default=300, verbose_name='часовой пояс автора, минут от UTC')),
                ('archived', models.BooleanField(default=False, verbose_name='в архиве')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_on', models.DateField(blank=True, null=True, verbose_name='с какого дня')),
                ('board', models.ForeignKey(blank=True, help_text='Пусто — личная привычка', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='tracker.board', verbose_name='общий трекер')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'привычка / дело',
                'verbose_name_plural': 'привычки и дела',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='день')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='сделано')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tracker.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'отметка',
                'verbose_name_plural': 'отметки',
            },
        ),
        migrations.AddConstraint(
            model_name='boardmember',
            constraint=models.UniqueConstraint(fields=('board', 'user'), name='one_tracker_membership'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['user', 'day'], name='tracker_hab_user_id_c57f26_idx'),
        ),
        migrations.AddConstraint(
            model_name='habitlog',
            constraint=models.UniqueConstraint(fields=('habit', 'user', 'day'), name='one_log_per_day'),
        ),
    ]
