# Generated by Django 5.2.17 on 2026-10-03 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_telegram_core'),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='ends_on',
            field=models.DateField(blank=True, help_text='Пусто — без срока. С датой — после неё видно победителя', null=True, verbose_name='соревнование до'),
        ),
        migrations.AddField(
            model_name='board',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.thread', verbose_name='чат трекера'),
        ),
        migrations.AddField(
            model_name='habit',
            name='note',
            field=models.CharField(blank=True, help_text='Например: «1 таблетка после еды»', max_length=200, verbose_name='заметка'),
        ),
        migrations.AddField(
            model_name='habit',
            name='part',
            field=models.CharField(blank=True, choices=[('', 'В любое время'), ('morning', 'Утро'), ('day', 'День'), ('evening', 'Вечер')], default='', max_length=8, verbose_name='время дня'),
        ),
        migrations.AddField(
            model_name='habit',
            name='per_week',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 — по дням недели; 1–6 — столько раз в неделю, в любые дни', verbose_name='раз в неделю'),
        ),
        migrations.AddField(
            model_name='habit',
            name='reminders',
            field=models.CharField(blank=True, help_text='Через запятую: 08:00,14:00,20:00', max_length=60, verbose_name='напоминания'),
        ),
        migrations.AddField(
            model_name='habitlog',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='заметка'),
        ),
        migrations.AddField(
            model_name='habitlog',
            name='skipped',
            field=models.BooleanField(default=False, help_text='Болезнь, дорога — день не считается и серию не рвёт', verbose_name='пропуск по уважительной причине'),
        ),
    ]
