# Generated by Django 5.2.17 on 2026-09-18 19:37

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='название')),
                ('slug', models.SlugField(unique=True, verbose_name='слаг')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('icon', models.CharField(default='📦', max_length=8, verbose_name='иконка')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='заголовок')),
                ('description', models.TextField(verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='цена')),
                ('currency', models.CharField(choices=[('UZS', 'сум'), ('USD', '$'), ('RUB', '₽')], default='UZS', max_length=3, verbose_name='валюта')),
                ('city', models.CharField(max_length=80, verbose_name='город')),
                ('contact', models.CharField(blank=True, help_text='Пусто — покажем email из профиля', max_length=100, verbose_name='контакт (телефон/ник)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='listings/%Y/%m/', verbose_name='фото')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Опубликован'), ('rejected', 'Отклонён')], default='pending', max_length=10, verbose_name='статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
                ('boosted_until', models.DateTimeField(blank=True, null=True, verbose_name='буст до')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='market.category', verbose_name='категория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
                'ordering': ['-boosted_until', '-created_at'],
            },
        ),
    ]
