# Generated by Django 5.2.17 on 2026-10-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_seed_and_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(choices=[('UZS', 'UZS — сум'), ('USD', 'USD — доллар'), ('EUR', 'EUR — евро'), ('RUB', 'RUB — рубль'), ('KZT', 'KZT — тенге'), ('KGS', 'KGS — сом'), ('TJS', 'TJS — сомони'), ('UAH', 'UAH — гривна'), ('TRY', 'TRY — лира'), ('SAR', 'SAR — риял'), ('AED', 'AED — дирхам'), ('EGP', 'EGP — ег. фунт'), ('GBP', 'GBP — фунт')], default='UZS', max_length=3, verbose_name='валюта'),
        ),
    ]
