# Generated by Django 5.2.17 on 2026-09-18 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True, verbose_name='ключ (имя раздела)')),
                ('name', models.CharField(max_length=80, verbose_name='название')),
                ('status', models.CharField(choices=[('on', 'включён'), ('off', 'выключен'), ('soon', 'скоро')], default='soon', max_length=4, verbose_name='статус')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('icon', models.CharField(default='✦', help_text='Эмодзи для витрины разделов; SVG-иконки появятся по фазам', max_length=8, verbose_name='иконка')),
                ('in_grid', models.BooleanField(default=True, verbose_name='показывать на главной')),
            ],
            options={
                'verbose_name': 'раздел',
                'verbose_name_plural': 'разделы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('accent', models.CharField(max_length=9, verbose_name='акцент')),
                ('accent_d', models.CharField(max_length=9, verbose_name='акцент тёмный')),
                ('accent_soft', models.CharField(max_length=9, verbose_name='акцент мягкий')),
                ('is_dark', models.BooleanField(default=False, verbose_name='тёмная тема')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'тема оформления',
                'verbose_name_plural': 'темы оформления',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='ссылка')),
                ('read', models.BooleanField(default=False, verbose_name='прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'уведомление',
                'verbose_name_plural': 'уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ilm4', max_length=50, verbose_name='название сайта')),
                ('hadis_enabled', models.BooleanField(default=True, verbose_name='хадис дня включён')),
                ('hadis_text', models.TextField(default='«Поистине, дела оцениваются по намерениям».', verbose_name='хадис дня — текст')),
                ('hadis_source', models.CharField(default='аль-Бухари, Муслим', max_length=200, verbose_name='хадис дня — источник')),
                ('news_ticker', models.BooleanField(default=False, verbose_name='бегущая строка новостей')),
                ('support_text', models.TextField(default='ilm4 живёт на пожертвования уммы — садака джария, пока люди получают знания и пользу.', verbose_name='текст «Поддержать проект»')),
                ('default_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.theme', verbose_name='тема по умолчанию')),
            ],
            options={
                'verbose_name': 'настройки сайта',
            },
        ),
    ]
