# Generated by Django 5.2.17 on 2026-09-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_themes_and_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='min_payout',
            field=models.PositiveIntegerField(default=100000, verbose_name='минимальная сумма вывода, сум'),
        ),
    ]
