# Generated by Django 5.2.17 on 2026-09-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_min_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='prayer_method',
            field=models.CharField(default='Karachi', help_text='Karachi (СНГ/Азия), MWL, ISNA, Makkah, Egypt', max_length=10, verbose_name='метод расчёта намаза'),
        ),
    ]
