# Generated by Django 5.2.17 on 2026-09-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_prayer_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='doctor_publish_price',
            field=models.PositiveIntegerField(default=0, verbose_name='цена публикации врача, сум (0 — бесплатно)'),
        ),
    ]
