# Generated by Django 5.2.17 on 2026-09-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_doctor_publish_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='boost_price',
            field=models.PositiveIntegerField(default=20000, verbose_name='цена буста объявления (7 дней), сум'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='market_moderation',
            field=models.BooleanField(default=True, help_text='Выключи, если объявлений слишком много для ручной проверки', verbose_name='модерация объявлений ilmbuy'),
        ),
    ]
