# Generated by Django 5.2.17 on 2026-09-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_boost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='nikah_boost_price',
            field=models.PositiveIntegerField(default=15000, verbose_name='никах: цена буста анкеты (7 дней), сум'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nikah_chat_price',
            field=models.PositiveIntegerField(default=10000, verbose_name='никах: цена «написать» для мужчин, сум'),
        ),
    ]
