# Generated by Django 5.2.17 on 2026-09-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_nikah_boost_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='картинка 1600×500')),
                ('title', models.CharField(max_length=120, verbose_name='заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='подпись')),
                ('cta_text', models.CharField(default='Подробнее', max_length=40, verbose_name='надпись кнопки')),
                ('cta_url', models.CharField(default='/', max_length=300, verbose_name='ссылка кнопки')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
            ],
            options={
                'verbose_name': 'баннер',
                'verbose_name_plural': 'баннеры (реклама на главной)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='код валюты')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='курс к суму')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'курс валюты',
                'verbose_name_plural': 'курсы валют',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hadis_image',
            field=models.ImageField(blank=True, help_text='Фон карточки хадиса на главной; без неё — фирменный градиент', null=True, upload_to='settings/', verbose_name='хадис — фоновая картинка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Иллюстрация в правой части главного баннера', null=True, upload_to='settings/', verbose_name='герой — картинка справа'),
        ),
        migrations.AlterField(
            model_name='moduleconfig',
            name='icon',
            field=models.CharField(default='✦', help_text='Эмодзи-фоллбек: если в static/img/icons/ есть <ключ>.svg или .png — показывается он', max_length=8, verbose_name='иконка'),
        ),
    ]
