# Generated by Django 5.2.17 on 2026-09-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_banner_rate_sitesettings_hadis_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='duration_seconds',
            field=models.PositiveSmallIntegerField(default=6, help_text='Сколько секунд слайд висит + сколько секунд заполняется линия', verbose_name='секунд показа'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hadis_details',
            field=models.TextField(blank=True, help_text='Кто передал, откуда хадис, пояснение. Показывается по кнопке «i»', verbose_name='хадис дня — разбор (кнопка «i»)'),
        ),
    ]
