# Generated by Django 5.2.17 on 2026-09-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_modules_fun_lawyers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('x', 'X (Twitter)'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('vk', 'ВКонтакте'), ('threads', 'Threads'), ('other', 'Другое')], default='telegram', max_length=12, verbose_name='сеть')),
                ('title', models.CharField(blank=True, help_text='Например: «новости» — будет «Telegram · новости»', max_length=40, verbose_name='подпись')),
                ('url', models.URLField(verbose_name='ссылка')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='показывать')),
            ],
            options={
                'verbose_name': 'соцсеть',
                'verbose_name_plural': 'соцсети и каналы',
                'ordering': ['order', 'id'],
            },
        ),
    ]
