# Generated by Django 5.2.17 on 2026-09-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_seed_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='wallet_payouts_enabled',
            field=models.BooleanField(default=False, help_text='Вывод и переводы между людьми делают кошелёк платёжным сервисом — обычно нужна лицензия. Без вывода баланс — предоплата за услуги платформы.', verbose_name='кошелёк: вывод средств включён'),
        ),
    ]
