# Generated by Django 5.2.17 on 2026-09-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_module_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='chat_photos_enabled',
            field=models.BooleanField(default=False, help_text='Основа заложена; включать, когда будет готова модерация вложений', verbose_name='чат: отправка фото'),
        ),
    ]
