# Generated by Django 5.2.17 on 2026-09-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_messenger_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='chat_calls_enabled',
            field=models.BooleanField(default=True, verbose_name='чат: аудиозвонки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_circles_enabled',
            field=models.BooleanField(default=True, verbose_name='чат: видеокружки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_video_calls_enabled',
            field=models.BooleanField(default=True, verbose_name='чат: видеозвонки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_voice_enabled',
            field=models.BooleanField(default=True, verbose_name='чат: голосовые сообщения'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='webrtc_turn_credential',
            field=models.CharField(blank=True, max_length=100, verbose_name='звонки: TURN пароль'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='webrtc_turn_url',
            field=models.CharField(blank=True, help_text='Например: turn:turn.ilm4.com:3478. Без TURN часть звонков через мобильные сети не соединится', max_length=200, verbose_name='звонки: TURN-сервер'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='webrtc_turn_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='звонки: TURN логин'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='chat_photos_enabled',
            field=models.BooleanField(default=True, verbose_name='чат: фото'),
        ),
    ]
