# Generated by Django 5.2.17 on 2026-09-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_enable_messenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='escrow_auto_release_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='Если заказчик не принял и не открыл спор — деньги уходят исполнителю', verbose_name='автопринятие работы через, дней'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='escrow_enabled',
            field=models.BooleanField(default=False, help_text='Платформа удерживает деньги заказчика до сдачи работы. Удержание чужих денег обычно требует лицензии или платёжного партнёра — включать после консультации юриста.', verbose_name='безопасная сделка (эскроу) включена'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='escrow_fee_percent',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=4, verbose_name='комиссия безопасной сделки, %'),
        ),
    ]
