# Generated by Django 5.2.17 on 2026-09-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_escrow_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='chat_contacts_enabled',
            field=models.BooleanField(default=True, verbose_name='чат: «Найти знакомых из контактов»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feed_enabled',
            field=models.BooleanField(default=True, verbose_name='лента (/feed/) включена'),
        ),
    ]
