# Generated by Django 5.2.17 on 2026-09-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_feed_contacts_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_maptiler_key',
            field=models.CharField(blank=True, help_text='cloud.maptiler.com → API keys. В настройках ключа разрешите только свой домен. Без ключа карта работает на запасных подложках (OpenStreetMap, Esri)', max_length=80, verbose_name='карта: ключ MapTiler'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nikah_photo_minutes',
            field=models.PositiveSmallIntegerField(default=10, help_text='Сколько длится одноразовый показ фото при взаимной симпатии', verbose_name='никях: минут на просмотр фото'),
        ),
    ]
