# Generated by Django 5.2.17 on 2026-09-23 19:14

from django.db import migrations, models


def free_nikah_chat(apps, schema_editor):
    # старое значение по умолчанию (10 000) — пока пополнение не подключено, чат для брата бесплатный
    apps.get_model('core', 'SiteSettings').objects.filter(nikah_chat_price=10_000).update(nikah_chat_price=0)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_map_key_mosque_manhaj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='nikah_chat_price',
            field=models.PositiveIntegerField(default=0, help_text='0 — бесплатно. Сёстрам всегда бесплатно. Пока пополнение баланса не подключено — оставьте 0', verbose_name='никях: цена открытия чата для брата (после взаимной симпатии), сум'),
        ),
        migrations.RunPython(free_nikah_chat, migrations.RunPython.noop),
    ]
