# Generated by Django 5.2.17 on 2026-09-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_nikah_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='nikah_daily_limit',
            field=models.PositiveSmallIntegerField(default=20, help_text='Сколько анкет можно просмотреть (свайпнуть) за сутки. С премиумом — без ограничения', verbose_name='никях: анкет в день (без премиума)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nikah_premium_days',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='никях: премиум, дней'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nikah_premium_enabled',
            field=models.BooleanField(default=True, verbose_name='никях: премиум включён'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nikah_premium_price',
            field=models.PositiveIntegerField(default=49000, verbose_name='никях: цена премиума, сум'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nikah_restore_price',
            field=models.PositiveIntegerField(default=10000, help_text='С премиумом — бесплатно', verbose_name='никях: «вернуть отклонённых», сум'),
        ),
    ]
