# Generated by Django 5.2.17 on 2026-09-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_nikah_swipe_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='nikah_ref_bonus_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='Начисляется, когда анкету приглашённого одобрит модератор', verbose_name='никях: дней премиума за приглашённого'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stars_rate',
            field=models.PositiveIntegerField(default=250, help_text='Пополнение через Stars: сумма в сум ÷ курс = сколько звёзд списать', verbose_name='Telegram Stars: сум за 1 звезду'),
        ),
    ]
