# Generated by Django 5.2.17 on 2026-09-23 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0023_nikah_verify_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('reason', models.CharField(choices=[('spam', 'Спам или реклама'), ('fraud', 'Мошенничество, просят предоплату'), ('haram', 'Харам, неприличное содержание'), ('fake', 'Фейк, чужие фото, обман'), ('contacts', 'Контакты в анкете / уводят в другие мессенджеры'), ('abuse', 'Оскорбления, угрозы'), ('other', 'Другое')], max_length=10, verbose_name='причина')),
                ('text', models.CharField(blank=True, max_length=500, verbose_name='подробности')),
                ('status', models.CharField(choices=[('new', 'новая'), ('resolved', 'меры приняты'), ('dismissed', 'отклонена')], db_index=True, default='new', max_length=10, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='когда')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'жалоба',
                'verbose_name_plural': 'жалобы',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'reporter'), name='one_report_per_user')],
            },
        ),
    ]
