# Generated by Django 5.2.17 on 2026-09-24 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0024_reports_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ai_auto_approve',
            field=models.BooleanField(default=False, help_text='Выключено — ИИ только подсказывает модератору. Включено — «чисто» публикуется без человека', verbose_name='ИИ одобряет чистые публикации сам'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_check_photos',
            field=models.BooleanField(default=False, help_text='Фото уходит во внешний сервис ИИ. Включайте, только если это указано в политике конфиденциальности', verbose_name='ИИ проверяет фото анкет никяха'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_moderation_enabled',
            field=models.BooleanField(default=True, help_text='Работает, когда в .env задан ANTHROPIC_API_KEY или OPENAI_API_KEY', verbose_name='ИИ-модерация включена'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nikah_chat_block_contacts',
            field=models.BooleanField(default=True, help_text='Телефоны, ники и ссылки в переписке никяха не отправляются', verbose_name='никях: блокировать контакты в чате'),
        ),
        migrations.CreateModel(
            name='AIReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('content_hash', models.CharField(editable=False, max_length=64)),
                ('verdict', models.CharField(choices=[('ok', 'чисто'), ('review', 'посмотреть человеку'), ('reject', 'нарушение'), ('error', 'ошибка проверки')], max_length=8, verbose_name='вердикт ИИ')),
                ('reasons', models.JSONField(blank=True, default=list, verbose_name='причины')),
                ('model_name', models.CharField(blank=True, max_length=60, verbose_name='модель')),
                ('checked_at', models.DateTimeField(auto_now=True, verbose_name='проверено')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'проверка ИИ',
                'verbose_name_plural': 'проверки ИИ',
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='one_ai_review')],
            },
        ),
    ]
