# Generated by Django 5.2.17 on 2026-09-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_ai_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='chat_videos_enabled',
            field=models.BooleanField(default=True, verbose_name='чат: видео (файлом, до 50 МБ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nikah_chat_media',
            field=models.BooleanField(default=False, help_text='Выключено — в переписке пары никяха только текст и голос: фото показываются лишь через защищённый обмен (водяной знак, таймер)', verbose_name='никях-чат: фото, видео и кружки'),
        ),
    ]
