# Generated by Django 5.2.17 on 2026-09-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_chat_video_nikah_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='app_min_version',
            field=models.CharField(blank=True, help_text='Например 1.2.0. Кто на более старой версии — увидит «Обновите приложение». Пусто — без проверки', max_length=20, verbose_name='приложение: минимальная версия'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='app_notice',
            field=models.CharField(blank=True, help_text='Короткое сообщение всем пользователям приложения (например, о работах на сервере)', max_length=300, verbose_name='приложение: объявление вверху'),
        ),
    ]
