# Generated by Django 5.2.17 on 2026-09-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_sitesettings_app_min_version_sitesettings_app_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='phone_for_nikah',
            field=models.BooleanField(default=True, help_text='Войти в никях (анкета, лента) — только с подтверждённым номером: новый аккаунт ради обхода дневного лимита не создать', verbose_name='подтверждённый номер — для никяха'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_for_publish',
            field=models.BooleanField(default=True, help_text='Подавать объявления, вакансии, услуги и т.д. можно только с номером, подтверждённым через Telegram (один номер — один аккаунт). Смотреть можно всем. Работает, когда подключён Telegram-бот; сотрудников не касается', verbose_name='подтверждённый номер — для публикаций'),
        ),
    ]
