# Generated by Django 5.2.17 on 2026-09-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_phone_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='phone_for_contacts',
            field=models.BooleanField(default=True, help_text='Поиск знакомых по контактам телефона — только тем, чей номер подтверждён', verbose_name='подтверждённый номер — для «найти знакомых»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_for_money',
            field=models.BooleanField(default=True, help_text='Безопасная сделка и вывод на карту — только с номером (защита от «отмывания» краденых карт)', verbose_name='подтверждённый номер — для сделок и вывода денег'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_for_reviews',
            field=models.BooleanField(default=True, help_text='Отзывы и оценки — только с номером (иначе накрутка отзывов с новых почт)', verbose_name='подтверждённый номер — для отзывов'),
        ),
    ]
