# Generated by Django 5.2.17 on 2026-09-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_phone_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='newbie_manual_count',
            field=models.PositiveSmallIntegerField(default=3, help_text='Сколько первых публикаций нового автора всегда проверяет модератор — даже если ИИ их пропустил или купля-продажа без модерации. 0 — правило выключено', verbose_name='первые публикации новичка — только вручную'),
        ),
    ]
