# Generated by Django 5.2.17 on 2026-10-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_newbie'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='silent',
            field=models.BooleanField(default=False, help_text='Пуш придёт без звука (сообщение «отправить без звука»)', verbose_name='без звука'),
        ),
    ]
