# Generated by Django 5.2.17 on 2026-10-02 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_keys_silent_scheduled'),
        ('core', '0031_notification_silent'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.thread', verbose_name='переписка (жалоба из чата)'),
        ),
    ]
