# Generated by Django 5.2.17 on 2026-10-02 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_report_thread'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='chat_file_max_mb',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='чат: файл не больше, МБ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_files_enabled',
            field=models.BooleanField(default=True, help_text='«Отправить файлом»: документы, а также фото и видео в исходном качестве', verbose_name='чат: файлы без сжатия'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_video_height',
            field=models.PositiveSmallIntegerField(choices=[(480, '480p — экономно'), (720, '720p — как в Telegram'), (1080, '1080p — высокое')], default=720, help_text='Видео, отправленное как видео, пережимается на сервере до этого качества (исходник больше не хранится). Чтобы отправить без сжатия — «Отправить файлом»', verbose_name='чат: качество видео после сжатия'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_user',
            field=models.ForeignKey(blank=True, help_text='С ним открывается чат «Поддержка ilm4». Пусто — кнопки поддержки в чатах нет', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='аккаунт поддержки'),
        ),
    ]
