# Generated by Django 5.2.17 on 2026-10-02 11:53

from django.db import migrations, models


def raise_limit(apps, schema_editor):
    """Прежний предел 100 МБ был значением по умолчанию — поднимаем до 2 ГБ; своё значение не трогаем."""
    apps.get_model('core', 'SiteSettings').objects.filter(chat_file_max_mb=100).update(chat_file_max_mb=2000)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_chat_context_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='chat_daily_upload_mb',
            field=models.PositiveIntegerField(default=10000, help_text='Защита диска сервера от того, кто решит завалить его файлами. 0 — без ограничения', verbose_name='чат: один человек в сутки загружает не больше, МБ'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='chat_file_max_mb',
            field=models.PositiveSmallIntegerField(default=2000, help_text='2000 МБ ≈ 2 ГБ, как в Telegram. Большие файлы загружаются частями и продолжаются после обрыва связи', verbose_name='чат: файл не больше, МБ'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='chat_videos_enabled',
            field=models.BooleanField(default=True, verbose_name='чат: видео'),
        ),
        migrations.RunPython(raise_limit, migrations.RunPython.noop),
    ]
