# Generated by Django 5.2.17 on 2026-10-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_chat_big_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_currency',
            field=models.CharField(default='USD', help_text='Код валюты (USD, UZS, RUB…). В ней показываем цены тем, чью страну не удалось определить. Каждый может выбрать свою в «Настройках»', max_length=3, verbose_name='валюта по умолчанию'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trips_moderation',
            field=models.BooleanField(default=False, help_text='Выключено — поездка публикуется сразу (она может быть уже сегодня). Первые публикации новичка всё равно проверяются вручную', verbose_name='модерация попутчиков'),
        ),
    ]
