# Generated by Django 5.2.17 on 2026-10-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_currency_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='chat_channels_enabled',
            field=models.BooleanField(default=True, help_text='Каналы мечетей, учителей, организаций. Выключено — раздел каналов и сами каналы скрыты', verbose_name='чат: каналы'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_channels_staff_only',
            field=models.BooleanField(default=False, help_text='Включите, если хотите сами заводить каналы (мечети, учителя), а людям — только подписываться', verbose_name='чат: каналы создают только сотрудники'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_group_max_members',
            field=models.PositiveIntegerField(default=1000, verbose_name='чат: в группе не больше, человек'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_groups_enabled',
            field=models.BooleanField(default=True, help_text='Выключено — новые группы создавать нельзя, существующие скрыты', verbose_name='чат: группы'),
        ),
    ]
