# Generated by Django 5.2.17 on 2026-10-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_module_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='assistant_daily_free',
            field=models.PositiveSmallIntegerField(default=10, help_text='На ключе площадки (ANTHROPIC_API_KEY). Со своим ключом человек пишет без лимита. 0 — только свой ключ', verbose_name='ИИ-помощник: бесплатных сообщений в день'),
        ),
    ]
