# Generated by Django 5.2.17 on 2026-10-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_module_communities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='заголовок')),
                ('text', models.CharField(max_length=160, verbose_name='текст (до 160 знаков)')),
                ('url', models.CharField(help_text='Адрес на ilm4 (/buy/12/, /c/kanal/) или https://…', max_length=300, verbose_name='ссылка')),
                ('button', models.CharField(default='Перейти', max_length=24, verbose_name='надпись кнопки')),
                ('image', models.ImageField(blank=True, upload_to='ads/', verbose_name='картинка (необязательно)')),
                ('in_channels', models.BooleanField(default=True, verbose_name='показывать в открытых каналах')),
                ('in_feed', models.BooleanField(default=True, verbose_name='показывать в ленте')),
                ('in_home', models.BooleanField(default=True, verbose_name='показывать на главной')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='показывать с')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='показывать до')),
                ('is_active', models.BooleanField(default=True, verbose_name='включено')),
                ('impressions', models.PositiveIntegerField(default=0, editable=False, verbose_name='показов')),
                ('clicks', models.PositiveIntegerField(default=0, editable=False, verbose_name='переходов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
            ],
            options={
                'verbose_name': 'реклама',
                'verbose_name_plural': 'реклама',
                'ordering': ['-created_at'],
            },
        ),
    ]
