# Generated by Django 5.2.17 on 2026-10-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_scrub_chat_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_design',
            field=models.CharField(choices=[('classic', 'ilm4 — как сейчас'), ('telegram', 'Как Telegram'), ('avito', 'Как Авито'), ('insta', 'Как Instagram'), ('x', 'Как X')], default='classic', help_text='Оболочка (нижняя панель, шапка), которую видит новый человек и гость.', max_length=12, verbose_name='дизайн по умолчанию'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_desk',
            field=models.CharField(choices=[('all', 'Всё сразу'), ('talk', 'Общение'), ('market', 'Покупки и работа'), ('faith', 'Вера и привычки'), ('social', 'Лента и люди')], default='all', help_text='Готовый набор: какие кнопки внизу и с чего открывается ilm4.', max_length=12, verbose_name='рабочий стол по умолчанию'),
        ),
    ]
