# Generated by Django 5.2.17 on 2026-09-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(db_index=True, max_length=80, verbose_name='страна')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='город')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('kind', models.CharField(choices=[('unhcr', 'УВКБ ООН'), ('embassy', 'Посольство'), ('redcrescent', 'Красный Полумесяц / Красный Крест'), ('ngo', 'Общественная организация'), ('other', 'Другое')], default='unhcr', max_length=15, verbose_name='тип')),
                ('phones', models.CharField(blank=True, help_text='Например: +90 312 000 00 00, +90 312 000 00 01', max_length=300, verbose_name='телефоны (через запятую)')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='адрес')),
                ('website', models.URLField(blank=True, verbose_name='сайт')),
                ('notes', models.TextField(blank=True, help_text='Часы работы, условия приёма, на что обратить внимание', verbose_name='примечания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'организации помощи беженцам',
                'ordering': ['country', 'name'],
            },
        ),
    ]
