# Generated by Django 5.2.17 on 2026-09-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugee', '0002_org_seed_and_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='region',
            field=models.CharField(blank=True, choices=[('intl', 'Весь мир'), ('asia', 'Азия'), ('europe', 'Европа'), ('mideast', 'Ближний Восток и Африка'), ('americas', 'Америка')], db_index=True, help_text='Пусто — определится по стране', max_length=10, verbose_name='регион'),
        ),
        migrations.AlterField(
            model_name='org',
            name='kind',
            field=models.CharField(choices=[('intl', 'Международная организация'), ('unhcr', 'УВКБ ООН'), ('embassy', 'Посольство'), ('redcrescent', 'Красный Полумесяц / Красный Крест'), ('ngo', 'Общественная организация'), ('lawyer', 'Адвокат / юридическая помощь'), ('other', 'Другое')], default='unhcr', max_length=15, verbose_name='тип'),
        ),
    ]
