# Generated by Django 5.2.17 on 2026-09-19 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(db_index=True, max_length=80, verbose_name='откуда')),
                ('to_city', models.CharField(db_index=True, max_length=80, verbose_name='куда')),
                ('type', models.CharField(choices=[('cargo', 'Грузоперевозка'), ('pax', 'Пассажирская перевозка'), ('both', 'Груз и пассажиры')], default='cargo', max_length=6, verbose_name='тип')),
                ('ride_date', models.DateField(blank=True, help_text='Если поездка разовая', null=True, verbose_name='дата поездки')),
                ('price_text', models.CharField(blank=True, max_length=120, verbose_name='цена (текстом)')),
                ('description', models.TextField(help_text='Что везёте, машина, вместимость, периодичность', verbose_name='описание')),
                ('contact', models.CharField(max_length=120, verbose_name='контакт')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Опубликован'), ('rejected', 'Отклонён')], default='pending', max_length=10, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'перевозка',
                'verbose_name_plural': 'перевозки',
                'ordering': ['-created_at'],
            },
        ),
    ]
