# Generated by Django 5.2.17 on 2026-09-23 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_ride_seed_and_enable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='company',
            field=models.CharField(blank=True, help_text='Название компании или имя перевозчика', max_length=120, verbose_name='перевозчик / компания'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['from_city', 'to_city'], name='transport_r_from_ci_3607b6_idx'),
        ),
    ]
