# Generated by Django 5.2.17 on 2026-10-02 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_company_route_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('driver', 'Еду на машине — возьму попутчиков'), ('passenger', 'Ищу машину')], default='driver', max_length=10, verbose_name='кто вы')),
                ('from_city', models.CharField(db_index=True, max_length=80, verbose_name='откуда')),
                ('to_city', models.CharField(db_index=True, max_length=80, verbose_name='куда')),
                ('via', models.CharField(blank=True, help_text='Через запятую — этих людей тоже можно подобрать по дороге', max_length=200, verbose_name='по пути (через какие города)')),
                ('departs_at', models.DateTimeField(db_index=True, verbose_name='выезд')),
                ('tz_offset', models.SmallIntegerField(blank=True, null=True, verbose_name='часовой пояс выезда (минут от UTC)')),
                ('car', models.CharField(blank=True, help_text='Марка и цвет: «Toyota Camry, белая»', max_length=80, verbose_name='машина')),
                ('seats', models.PositiveSmallIntegerField(default=1, help_text='Водителю — сколько свободных мест; пассажиру — сколько вас', verbose_name='мест')),
                ('front_seat', models.BooleanField(default=False, verbose_name='переднее место свободно')),
                ('price', models.DecimalField(decimal_places=0, default=0, help_text='0 — бесплатно, ради Аллаха', max_digits=12, verbose_name='цена за место')),
                ('currency', models.CharField(choices=[('UZS', 'UZS — сум'), ('USD', 'USD — доллар'), ('EUR', 'EUR — евро'), ('RUB', 'RUB — рубль'), ('KZT', 'KZT — тенге'), ('KGS', 'KGS — сом'), ('TJS', 'TJS — сомони'), ('UAH', 'UAH — гривна'), ('TRY', 'TRY — лира'), ('SAR', 'SAR — риял'), ('AED', 'AED — дирхам'), ('EGP', 'EGP — ег. фунт'), ('GBP', 'GBP — фунт')], default='USD', max_length=3, verbose_name='валюта')),
                ('audience', models.CharField(choices=[('any', 'Любые попутчики'), ('men', 'Только братья'), ('women', 'Только сёстры'), ('family', 'Семьи и сёстры с махрамом')], default='any', max_length=8, verbose_name='кого беру')),
                ('parcels', models.BooleanField(default=False, verbose_name='возьму посылку')),
                ('comment', models.TextField(blank=True, help_text='Место встречи, багаж, остановки на намаз', max_length=1000, verbose_name='комментарий')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Опубликован'), ('rejected', 'Отклонён')], default='pending', max_length=10, verbose_name='статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='показывать')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'поездка (попутчики)',
                'verbose_name_plural': 'попутчики',
                'ordering': ['departs_at'],
            },
        ),
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.PositiveSmallIntegerField(default=1, verbose_name='мест')),
                ('status', models.CharField(choices=[('pending', 'Ждёт ответа'), ('accepted', 'Подтверждено'), ('declined', 'Отказ'), ('cancelled', 'Отменена')], default='pending', max_length=10, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='transport.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'заявка на место',
                'verbose_name_plural': 'заявки на места',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['from_city', 'to_city', 'departs_at'], name='transport_t_from_ci_120bc8_idx'),
        ),
        migrations.AddConstraint(
            model_name='triprequest',
            constraint=models.UniqueConstraint(fields=('trip', 'user'), name='one_request_per_trip'),
        ),
    ]
