# Generated by Django 5.2.17 on 2026-09-23 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='сумма, сум')),
                ('provider', models.CharField(max_length=20, verbose_name='способ')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено, зачислено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], db_index=True, default='pending', max_length=10, verbose_name='статус')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='id у провайдера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='оплачено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'пополнение',
                'verbose_name_plural': 'пополнения',
                'ordering': ['-created_at'],
            },
        ),
    ]
