# Generated by Django 5.2.17 on 2026-09-18 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NikahProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Брат'), ('F', 'Сестра')], max_length=1, verbose_name='кто')),
                ('age', models.PositiveSmallIntegerField(verbose_name='возраст')),
                ('city', models.CharField(max_length=80, verbose_name='город')),
                ('about', models.TextField(verbose_name='о себе')),
                ('partner_expectations', models.TextField(blank=True, verbose_name='кого ищете')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='nikah/%Y/%m/', verbose_name='фото')),
                ('contact_hint', models.CharField(blank=True, help_text='Например: telegram @ник или email', max_length=200, verbose_name='как связаться (показывается после оплаты)')),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Опубликован'), ('rejected', 'Отклонён')], default='pending', max_length=10, verbose_name='статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='анкета активна')),
                ('boosted_until', models.DateTimeField(blank=True, null=True, verbose_name='буст до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nikah_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'анкета никаха',
                'verbose_name_plural': 'анкеты никаха',
                'ordering': ['-boosted_until', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NikahContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='оплачено')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nikah_contacts_made', to=settings.AUTH_USER_MODEL)),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_received', to='nikah.nikahprofile')),
            ],
            options={
                'verbose_name': 'контакт никаха',
                'verbose_name_plural': 'контакты никаха',
                'unique_together': {('from_user', 'to_profile')},
            },
        ),
    ]
