# Generated by Django 5.2.17 on 2026-09-23 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_encrypt_existing'),
        ('nikah', '0002_enable_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nikahprofile',
            name='age_from',
            field=models.PositiveSmallIntegerField(default=18, verbose_name='ищу возраст от'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='age_to',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='ищу возраст до'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='agreed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='приняты обязательства'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='aqida',
            field=models.CharField(blank=True, choices=[('sunna', 'Ахлю-с-Сунна (без уточнения)'), ('athari', 'Ахлю-ль-асар (асари)'), ('salafi', 'Саляфия'), ('ashari', 'Ашариты'), ('maturidi', 'Матуридиты'), ('sufi', 'Суфизм'), ('other', 'Другое / затрудняюсь')], max_length=10, verbose_name='вероубеждение'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='children_accept',
            field=models.CharField(blank=True, choices=[('yes', 'Да, приму'), ('discuss', 'Обсуждаемо'), ('no', 'Нет')], max_length=8, verbose_name='примет детей партнёра'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='children_want',
            field=models.CharField(blank=True, choices=[('yes', 'Да, хочу детей'), ('unsure', 'Пока не решил / Пока не решила'), ('no', 'Нет')], max_length=8, verbose_name='хочет детей'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='country',
            field=models.CharField(blank=True, max_length=80, verbose_name='страна'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='faith_answers',
            field=models.JSONField(blank=True, default=dict, help_text='Видит только модератор', verbose_name='закрытые ответы о религии'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='рост, см'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='look',
            field=models.CharField(blank=True, choices=[('full', 'Да, полная борода'), ('short', 'Да, короткая'), ('growing', 'Отращиваю'), ('none', 'Нет'), ('niqab', 'Ношу никаб'), ('hijab', 'Ношу хиджаб'), ('sometimes', 'Иногда'), ('none', 'Пока не ношу')], max_length=10, verbose_name='борода / покрытие'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='madhhab',
            field=models.CharField(blank=True, choices=[('hanafi', 'Ханафитский'), ('maliki', 'Маликитский'), ('shafii', 'Шафиитский'), ('hanbali', 'Ханбалитский'), ('none', 'Не придерживаюсь определённого')], max_length=8, verbose_name='мазхаб'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='manhaj_text',
            field=models.TextField(blank=True, verbose_name='вероубеждение и манхадж (своими словами)'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='marital',
            field=models.CharField(blank=True, choices=[('never', 'Не был женат / Не была замужем'), ('divorced', 'Разведён / Разведена'), ('widowed', 'Вдовец / Вдова'), ('married', 'Женат')], max_length=10, verbose_name='семейное положение'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='name',
            field=models.CharField(blank=True, max_length=40, verbose_name='имя или ник'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=80, verbose_name='национальность'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='photo_mode',
            field=models.CharField(choices=[('exchange', 'Открывать фото при взаимной симпатии'), ('none', 'Без фото — только переписка')], default='exchange', max_length=10, verbose_name='фото'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='photo_private',
            field=models.FileField(blank=True, editable=False, upload_to='nikah_private/', verbose_name='фото (зашифровано)'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='polygyny',
            field=models.CharField(blank=True, choices=[('no', 'Только единственной женой'), ('discuss', 'Готова обсуждать'), ('yes', 'Готова быть не первой женой')], max_length=8, verbose_name='готова быть не первой женой'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='prayer',
            field=models.CharField(blank=True, choices=[('five', 'Читаю все пять'), ('irregular', 'Читаю нерегулярно'), ('start', 'Хочу начать'), ('none', 'Не читаю')], max_length=10, verbose_name='намаз'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='quran',
            field=models.CharField(blank=True, choices=[('daily', 'Каждый день'), ('weekly', 'Несколько раз в неделю'), ('sometimes', 'Иногда'), ('learning', 'Учусь читать'), ('rarely', 'Редко')], max_length=10, verbose_name='чтение Корана'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='ready_when',
            field=models.CharField(blank=True, choices=[('soon', 'В ближайшие 1–3 месяца'), ('half', 'В течение полугода'), ('year', 'Через год'), ('later', 'Позже')], max_length=8, verbose_name='готов к никяху'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='relocation',
            field=models.CharField(blank=True, choices=[('stay', 'Останусь в своём городе'), ('country', 'Перееду в пределах страны'), ('abroad', 'Готов переехать за границу / Готова переехать за границу'), ('any', 'Куда угодно ради семьи')], max_length=8, verbose_name='переезд'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='изменено'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='вес, кг'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='where_allah',
            field=models.CharField(blank=True, choices=[('above', 'Над Троном, над небесами — как Он описал Себя'), ('no_place', 'Он существует без места'), ('everywhere', 'Везде'), ('unsure', 'Затрудняюсь ответить')], max_length=10, verbose_name='где Аллах'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='wife_number',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Первую'), (2, 'Вторую'), (3, 'Третью'), (4, 'Четвёртую')], null=True, verbose_name='ищу жену по счёту'),
        ),
        migrations.AlterField(
            model_name='nikahprofile',
            name='about',
            field=models.TextField(blank=True, verbose_name='о себе'),
        ),
        migrations.AlterField(
            model_name='nikahprofile',
            name='city',
            field=models.CharField(blank=True, max_length=80, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='nikahprofile',
            name='contact_hint',
            field=models.CharField(blank=True, max_length=200, verbose_name='как связаться (устарело)'),
        ),
        migrations.AlterField(
            model_name='nikahprofile',
            name='partner_expectations',
            field=models.TextField(blank=True, verbose_name='кого ищу'),
        ),
        migrations.AlterField(
            model_name='nikahprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='nikah/%Y/%m/', verbose_name='фото (старое, не показывается)'),
        ),
        migrations.CreateModel(
            name='NikahInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests_sent', to='nikah.nikahprofile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests_received', to='nikah.nikahprofile')),
            ],
            options={
                'verbose_name': 'интерес',
                'verbose_name_plural': 'интересы',
                'ordering': ['-created_at'],
                'unique_together': {('from_profile', 'to_profile')},
            },
        ),
        migrations.CreateModel(
            name='NikahMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('photos', 'обмен фото'), ('chat', 'чат открыт'), ('closed', 'не сложилось')], default='photos', max_length=8, verbose_name='этап')),
                ('sister_ok', models.BooleanField(blank=True, null=True, verbose_name='сестра согласна')),
                ('brother_ok', models.BooleanField(blank=True, null=True, verbose_name='брат согласен')),
                ('sister_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='сестра открыла фото брата')),
                ('brother_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='брат открыл фото сестры')),
                ('chat_paid', models.BooleanField(default=False, verbose_name='чат оплачен братом')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('brother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_brother', to='nikah.nikahprofile')),
                ('sister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_sister', to='nikah.nikahprofile')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.thread')),
            ],
            options={
                'verbose_name': 'пара',
                'verbose_name_plural': 'пары (взаимный интерес)',
                'ordering': ['-created_at'],
                'unique_together': {('sister', 'brother')},
            },
        ),
        migrations.CreateModel(
            name='NikahSaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='nikah.nikahprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nikah_saved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'profile')},
            },
        ),
        migrations.DeleteModel(
            name='NikahContact',
        ),
    ]
