# Generated by Django 5.2.17 on 2026-09-23 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikah', '0003_nikah_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='nikahmatch',
            name='brother_tg_msg',
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='nikahmatch',
            name='sister_tg_msg',
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='has_children',
            field=models.CharField(blank=True, choices=[('no', 'Нет'), ('yes', 'Есть')], max_length=4, verbose_name='есть свои дети'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='был(а) в сети'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='премиум до'),
        ),
        migrations.CreateModel(
            name='NikahSkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skips', to='nikah.nikahprofile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='nikah.nikahprofile')),
            ],
            options={
                'verbose_name': 'пропуск анкеты',
                'verbose_name_plural': 'пропуски анкет',
                'unique_together': {('from_profile', 'to_profile')},
            },
        ),
    ]
