# Generated by Django 5.2.17 on 2026-09-23 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikah', '0004_nikah_swipe_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='nikahprofile',
            name='ref_bonus_given',
            field=models.BooleanField(default=False, editable=False, verbose_name='бонус за приглашение начислен'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited', to='nikah.nikahprofile', verbose_name='пригласил(а)'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='verified',
            field=models.BooleanField(default=False, help_text='Модератор посмотрел видео-кружок в Telegram: живой человек, лицо совпадает', verbose_name='верифицирован(а) ✅'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='верификация'),
        ),
    ]
