# Generated by Django 5.2.17 on 2026-09-23 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikah', '0005_nikah_verify_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nikahprofile',
            name='witness',
            field=models.ForeignKey(blank=True, help_text='Видит переписку во всех чатах никяха этой анкеты', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nikah_witness_for', to=settings.AUTH_USER_MODEL, verbose_name='свидетель (махрам)'),
        ),
        migrations.AddField(
            model_name='nikahprofile',
            name='witness_token',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
    ]
