# Generated by Django 5.2.17 on 2026-10-03 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistantkey',
            options={'verbose_name': 'настройки ИИ-помощника', 'verbose_name_plural': 'настройки ИИ-помощника'},
        ),
        migrations.AddField(
            model_name='assistantkey',
            name='base_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='адрес API (для своего сервера)'),
        ),
        migrations.AddField(
            model_name='assistantkey',
            name='model',
            field=models.CharField(blank=True, max_length=80, verbose_name='модель'),
        ),
        migrations.AddField(
            model_name='assistantkey',
            name='provider',
            field=models.CharField(default='anthropic', max_length=20, verbose_name='поставщик ИИ'),
        ),
        migrations.AddField(
            model_name='assistantkey',
            name='read_chats',
            field=models.BooleanField(default=False, help_text='Тексты уходят поставщику ИИ. Чаты никяха не передаются никогда.', verbose_name='помощник может читать мои новые сообщения'),
        ),
        migrations.AddField(
            model_name='chat',
            name='api',
            field=models.CharField(default='anthropic', max_length=10, verbose_name='формат истории'),
        ),
        migrations.AlterField(
            model_name='assistantkey',
            name='hint',
            field=models.CharField(blank=True, max_length=12, verbose_name='последние знаки ключа'),
        ),
        migrations.AlterField(
            model_name='assistantkey',
            name='key_enc',
            field=models.TextField(blank=True, verbose_name='ключ (зашифрован)'),
        ),
        migrations.CreateModel(
            name='AssistantPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('until', models.DateField(blank=True, null=True, verbose_name='без лимита до (включительно)')),
                ('extra_daily', models.PositiveSmallIntegerField(default=0, verbose_name='плюс сообщений в день')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='заметка')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_plan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'подписка на ИИ-помощника',
                'verbose_name_plural': 'подписки на ИИ-помощника',
            },
        ),
    ]
