# Generated by Django 5.2.17 on 2026-09-23 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0006_encrypt_existing'),
        ('wallet', '0002_escrow_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('freelance', 'Фриланс / услуга'), ('ad', 'Реклама'), ('transport', 'Перевозка'), ('other', 'Другое')], default='freelance', max_length=10, verbose_name='вид')),
                ('title', models.CharField(max_length=160, verbose_name='что нужно сделать')),
                ('terms', models.TextField(help_text='Что именно сдаётся, объём, формат, правки', verbose_name='условия и результат')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='сумма, сум')),
                ('fee_percent', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='комиссия, %')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='срок сдачи')),
                ('status', models.CharField(choices=[('offered', 'Предложен'), ('accepted', 'Принят исполнителем'), ('funded', 'Оплачен, деньги удержаны'), ('delivered', 'Работа сдана'), ('completed', 'Завершён, выплачено'), ('disputed', 'Спор'), ('refunded', 'Деньги возвращены'), ('cancelled', 'Отменён')], db_index=True, default='offered', max_length=10, verbose_name='статус')),
                ('dispute_reason', models.TextField(blank=True, verbose_name='причина спора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('funded_at', models.DateTimeField(blank=True, null=True, verbose_name='оплачен')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='сдан')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='закрыт')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_placed', to=settings.AUTH_USER_MODEL, verbose_name='заказчик')),
                ('escrow', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='wallet.escrowdeal', verbose_name='удержание')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_taken', to=settings.AUTH_USER_MODEL, verbose_name='исполнитель')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='chat.thread')),
            ],
            options={
                'verbose_name': 'безопасная сделка',
                'verbose_name_plural': 'безопасные сделки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20, verbose_name='действие')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='когда')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='deals.order')),
            ],
            options={
                'verbose_name': 'событие сделки',
                'verbose_name_plural': 'события сделок',
                'ordering': ['created_at'],
            },
        ),
    ]
