# Generated by Django 5.2.17 on 2026-09-18 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='сумма, сум')),
                ('status', models.CharField(choices=[('hold', 'Деньги заморожены'), ('released', 'Выплачена продавцу'), ('refunded', 'Возвращена покупателю')], default='hold', max_length=10, verbose_name='статус')),
                ('ref', models.CharField(blank=True, max_length=120, verbose_name='объект')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='описание спора/решения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='решено')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_buys', to=settings.AUTH_USER_MODEL, verbose_name='покупатель')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_sells', to=settings.AUTH_USER_MODEL, verbose_name='продавец')),
            ],
            options={
                'verbose_name': 'эскроу-сделка',
                'verbose_name_plural': 'эскроу-сделки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='сумма, сум')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('done', 'Выполнена'), ('rejected', 'Отклонена')], default='pending', max_length=10, verbose_name='статус')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_decisions', to=settings.AUTH_USER_MODEL, verbose_name='кто решил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'заявка на вывод',
                'verbose_name_plural': 'заявки на вывод',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='сумма, сум')),
                ('kind', models.CharField(choices=[('topup', 'Пополнение'), ('earn', 'Зачисление'), ('purchase', 'Списание'), ('payout', 'Вывод'), ('escrow_hold', 'Эскроу: заморозка'), ('escrow_rel', 'Эскроу: выплата'), ('escrow_ref', 'Эскроу: возврат'), ('admin_adjust', 'Корректировка')], max_length=12, verbose_name='вид')),
                ('ref', models.CharField(blank=True, max_length=120, verbose_name='объект (модуль:действие:id)')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='заметка')),
                ('balance_after', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='баланс после')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'транзакция',
                'verbose_name_plural': 'транзакции',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='баланс, сум')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'кошелёк',
                'verbose_name_plural': 'кошельки',
            },
        ),
    ]
