# Generated by Django 5.2.17 on 2026-09-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowdeal',
            name='fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='комиссия платформы, сум'),
        ),
    ]
