# Generated by Django 5.2.17 on 2026-09-23 14:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(db_index=True, verbose_name='id объекта')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='оценка')),
                ('text', models.TextField(blank=True, max_length=2000, verbose_name='текст')),
                ('reply', models.TextField(blank=True, max_length=2000, verbose_name='ответ владельца')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='ответ дан')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='скрыт модератором')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='тип объекта')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'is_hidden'], name='reviews_rev_content_a19375_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'author'), name='one_review_per_author')],
            },
        ),
    ]
