# Generated by Django 5.2.17 on 2026-10-03 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='название')),
                ('emoji', models.CharField(blank=True, max_length=8, verbose_name='значок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gifts/', verbose_name='картинка')),
                ('price', models.PositiveIntegerField(default=0, help_text='0 — бесплатный', verbose_name='цена, сум')),
                ('active', models.BooleanField(default=True, verbose_name='в каталоге')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'подарок (каталог)',
                'verbose_name_plural': 'подарки (каталог)',
                'ordering': ['order', 'price', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(db_index=True, max_length=40, verbose_name='к чему')),
                ('text', models.TextField(max_length=2000, verbose_name='текст')),
                ('hidden', models.BooleanField(default=False, verbose_name='скрыт')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='social.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=4000, verbose_name='текст')),
                ('privacy', models.CharField(choices=[('all', 'Все'), ('close', 'Близкие друзья')], default='all', max_length=6, verbose_name='кто видит')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='лайков')),
                ('comments', models.PositiveIntegerField(default=0, verbose_name='комментариев')),
                ('reposts', models.PositiveIntegerField(default=0, verbose_name='репостов')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='просмотров')),
                ('hidden', models.BooleanField(db_index=True, default=False, verbose_name='скрыта модератором')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создана')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='изменена')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('repost_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts_set', to='social.post', verbose_name='репост записи')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/%Y/%m/', verbose_name='фото')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='social.post')),
            ],
            options={
                'verbose_name': 'фото записи',
                'verbose_name_plural': 'фото записей',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='shorts/%Y/%m/', verbose_name='видео')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='shorts/%Y/%m/', verbose_name='обложка')),
                ('caption', models.CharField(blank=True, max_length=500, verbose_name='подпись')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='длительность, сек')),
                ('status', models.CharField(choices=[('pending', 'на проверке'), ('approved', 'опубликовано'), ('rejected', 'отклонено')], db_index=True, default='pending', max_length=9)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shorts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'короткое видео',
                'verbose_name_plural': 'короткие видео',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео')], default='photo', max_length=6)),
                ('media', models.FileField(upload_to='stories/%Y/%m/', verbose_name='файл')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='подпись')),
                ('privacy', models.CharField(choices=[('all', 'Все'), ('close', 'Близкие друзья')], default='all', max_length=6, verbose_name='кто видит')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='исчезнет')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'сторис',
                'verbose_name_plural': 'сторис',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=200, verbose_name='подпись')),
                ('anonymous', models.BooleanField(default=False, verbose_name='скрыть отправителя')),
                ('on_profile', models.BooleanField(default=True, verbose_name='показывать в профиле')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent', to='social.gift')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifts_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'подарок',
                'verbose_name_plural': 'подарки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'подписка',
                'verbose_name_plural': 'подписки',
                'constraints': [models.UniqueConstraint(fields=('follower', 'author'), name='one_follow')],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(db_index=True, max_length=40, verbose_name='что')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'лайк',
                'verbose_name_plural': 'лайки',
                'constraints': [models.UniqueConstraint(fields=('user', 'target'), name='one_like')],
            },
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(blank=True, max_length=16)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_by', to='social.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories_seen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('story', 'user'), name='one_story_view')],
            },
        ),
    ]
