# Generated by Django 5.2.17 on 2026-10-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='approved',
            field=models.BooleanField(default=True, verbose_name='одобрена'),
        ),
    ]
