"""API мобильного приложения: /api/v1/… (JSON, вход по токену)."""
from django.urls import path

from . import views_account as a
from . import views_assistant as ai
from . import views_chat as c
from . import views_content as v
from . import views_nikah as n
from . import views_people as u
from . import views_pubs as m
from . import views_social as so
from . import views_spaces as sp
from . import views_tracker as t

app_name = 'api'

urlpatterns = [
    path('config/', a.config),
    path('home/', a.home),
    path('auth/login/', a.login),
    path('auth/register/', a.register),
    path('auth/logout/', a.logout),
    path('auth/password-reset/', a.password_reset),
    path('auth/telegram/start/', a.telegram_start),
    path('auth/telegram/poll/', a.telegram_poll),
    path('auth/sessions/', a.sessions),
    path('auth/qr/<str:token>/', a.qr_login),
    path('auth/web-link/', a.web_link),
    path('auth/web/<str:code>/', a.web_enter),
    path('auth/phone/', a.phone_start),
    path('auth/phone/status/', a.phone_status),
    path('me/', a.me),
    path('push/', a.push_register),
    path('notifications/', a.notifications),
    path('notifications/read/', a.notifications_read),
    path('wallet/', a.wallet),
    path('report/', a.report),
    path('block/', a.block),
    path('ping/', u.ping),
    path('me/links/', u.my_links),
    path('me/photos/', u.my_photos),
    path('me/close/', u.close_friends),
    path('me/personas/', a.personas),
    path('home/showcase/', a.showcase),
    path('people/', u.people_list),
    path('contacts/', u.contacts),
    path('chat/find/', c.find),
    path('users/<int:pk>/', u.user),
    path('users/<int:pk>/chat/', u.user_chat),
    path('users/<int:pk>/close/', u.user_close),

    path('news/', v.news),
    path('news/<int:pk>/', v.news_detail),
    path('places/map/', v.places_map),
    path('my/', m.my),
    path('my/<str:key>/<int:pk>/', m.my_item),
    path('pubs/<str:key>/form/', m.form_schema),
    path('pubs/<str:key>/save/', m.save),
    path('pubs/<str:key>/', v.pubs),
    path('pubs/<str:key>/<int:pk>/', v.pub_detail),
    path('pubs/<str:key>/<int:pk>/message/', v.pub_message),
    path('forum/<int:pk>/reply/', v.topic_reply),
    path('trips/<int:pk>/request/', v.trip_request),
    path('trips/request/<int:req_id>/<str:action>/', v.trip_request_act),

    path('nikah/state/', n.state),
    path('nikah/options/', n.options),
    path('nikah/profile/', n.profile_save),
    path('nikah/profile/raw/', n.profile_raw),
    path('nikah/pause/', n.pause),
    path('nikah/feed/', n.feed),
    path('nikah/lists/', n.lists),
    path('nikah/restore/', n.restore),
    path('nikah/premium/', n.premium),
    path('nikah/p/<int:pk>/', n.profile_detail),
    path('nikah/p/<int:pk>/skip/', n.skip),
    path('nikah/p/<int:pk>/interest/', n.interest),
    path('nikah/p/<int:pk>/save/', n.save_toggle),
    path('nikah/match/<int:pk>/', n.match),
    path('nikah/match/<int:pk>/open/', n.match_open),
    path('nikah/match/<int:pk>/photo/', n.match_photo),
    path('nikah/match/<int:pk>/decide/', n.match_decide),
    path('nikah/match/<int:pk>/pay/', n.match_pay),

    path('assistant/', ai.state),
    path('assistant/send/', ai.send),
    path('assistant/key/', ai.key),
    path('assistant/<int:chat_id>/delete/', ai.delete),
    path('communities/', sp.index),
    path('communities/new/', sp.new),
    path('communities/join/<str:code>/', sp.join),
    path('communities/<int:pk>/', sp.detail),
    path('communities/<int:pk>/act/', sp.act),
    path('communities/<int:pk>/board/', sp.board),

    path('feed/', so.feed),
    path('feed/new/', so.post_new),
    path('feed/like/', so.like),
    path('feed/requests/', so.follow_requests),
    path('feed/save/', so.save),
    path('feed/saved/', so.saved),
    path('metrics/', so.metrics),
    path('feed/comments/', so.comments),
    path('feed/comment/<int:pk>/delete/', so.comment_delete),
    path('feed/post/<int:pk>/<str:action>/', so.post_act),
    path('feed/wall/<int:user_id>/', so.wall),
    path('feed/stories/', so.stories),
    path('feed/stories/new/', so.story_new),
    path('feed/stories/<int:pk>/<str:action>/', so.story_act),
    path('feed/gifts/', so.gifts),
    path('users/<int:user_id>/follow/', so.follow),
    path('users/<int:user_id>/gift/', so.gift_send),

    path('tracker/', t.day),
    path('tracker/stats/', t.stats),
    path('tracker/habits/', t.habits),
    path('tracker/habits/new/', t.habit_create),
    path('tracker/habits/<int:pk>/', t.habit),
    path('tracker/habits/<int:pk>/log/', t.habit_log),
    path('tracker/habits/<int:pk>/detail/', t.habit_detail),
    path('tracker/templates/', t.templates),
    path('tracker/boards/<int:pk>/chat/', t.board_chat),
    path('tracker/boards/new/', t.board_create),
    path('tracker/boards/<int:pk>/', t.board),
    path('tracker/join/<str:code>/', t.board_join),

    path('chat/', c.threads),
    path('chat/file/<int:msg_id>/', c.file),
    path('chat/support/', c.support),
    path('chat/saved/', c.saved),
    path('chat/forward/', c.forward),
    path('chat/folders/', c.folders),
    path('chat/folders/<int:pk>/', c.folder),
    path('chat/<int:pk>/state/<str:action>/', c.state),
    path('chat/<int:pk>/draft/', c.draft),
    path('chat/<int:pk>/search/', c.search),
    path('chat/<int:pk>/post/<int:msg_id>/', c.post),
    path('chat/rooms/', c.rooms_catalog),
    path('chat/rooms/new/', c.room_create),
    path('chat/join/<str:code>/', c.room_link),
    path('chat/c/<str:handle>/', c.room_handle),
    path('chat/<int:pk>/mute/', c.mute),
    path('chat/<int:pk>/media/', c.media),
    path('chat/<int:pk>/room/', c.room),
    path('chat/<int:pk>/room/<str:action>/', c.room_act),
    path('chat/<int:pk>/member/<int:user_id>/<str:action>/', c.room_member),
    path('chat/<int:pk>/', c.messages),
    path('chat/<int:pk>/send/', c.send),
    path('chat/<int:pk>/upload/', c.upload),
    path('chat/<int:pk>/upload/begin/', c.upload_begin),
    path('chat/upload/<uuid:upload_id>/', c.upload_chunk),
    path('chat/upload/<uuid:upload_id>/<str:step>/', c.upload_chunk),
    path('chat/<int:pk>/read/', c.read),
    path('chat/msg/<int:msg_id>/<str:action>/', c.scheduled),
]
