# Generated by Django 5.2.17 on 2026-09-23 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_read_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat/%Y/%m/', verbose_name='вложение'),
        ),
        migrations.AddField(
            model_name='message',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='длительность, сек (голос/кружок/видео)'),
        ),
        migrations.AddField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('text', 'Текст'), ('photo', 'Фото'), ('video', 'Видео'), ('voice', 'Голосовое'), ('circle', 'Видеокружок'), ('file', 'Файл'), ('system', 'Служебное')], default='text', max_length=8, verbose_name='вид'),
        ),
        migrations.AddField(
            model_name='thread',
            name='kind',
            field=models.CharField(choices=[('direct', 'Личный'), ('group', 'Группа'), ('channel', 'Канал')], db_index=True, default='direct', max_length=8, verbose_name='вид'),
        ),
        migrations.AddField(
            model_name='thread',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_threads', to=settings.AUTH_USER_MODEL, verbose_name='создатель (группа/канал)'),
        ),
        migrations.AddField(
            model_name='thread',
            name='title',
            field=models.CharField(blank=True, max_length=120, verbose_name='название (группа/канал)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, verbose_name='текст'),
        ),
    ]
