# Generated by Django 5.2.17 on 2026-09-23 15:40

from django.db import migrations

import apps.chat.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_messenger_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=apps.chat.crypto.EncryptedTextField(blank=True, verbose_name='текст'),
        ),
    ]
