# Generated by Django 5.2.17 on 2026-10-02 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_body_enc_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadKey',
            fields=[
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='key', serialize=False, to='chat.thread')),
                ('kid', models.CharField(max_length=32, verbose_name='главный ключ (id)')),
                ('wrapped', models.TextField(verbose_name='ключ чата (зашифрован)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ключ чата',
                'verbose_name_plural': 'ключи чатов',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='отправить в (запланированное)'),
        ),
        migrations.AddField(
            model_name='message',
            name='silent',
            field=models.BooleanField(default=False, verbose_name='без звука'),
        ),
    ]
