# Generated by Django 5.2.17 on 2026-10-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_keys_silent_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='meta_enc',
            field=models.TextField(blank=True, verbose_name='сведения о вложении (зашифрованы)'),
        ),
        migrations.AddField(
            model_name='thread',
            name='context_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='объект раздела'),
        ),
        migrations.AddField(
            model_name='thread',
            name='context_type',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='раздел'),
        ),
    ]
