# Generated by Django 5.2.17 on 2026-10-02 11:53

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chat_context_files'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(default='file', max_length=8)),
                ('path', models.CharField(max_length=200, verbose_name='файл (внутри MEDIA_ROOT)')),
                ('size', models.BigIntegerField(verbose_name='полный размер, байт')),
                ('received', models.BigIntegerField(default=0, verbose_name='получено, байт')),
                ('info_enc', models.TextField(blank=True, verbose_name='имя, подпись, время отправки (зашифрованы)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='chat.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'загрузка файла',
                'verbose_name_plural': 'загрузки файлов',
            },
        ),
    ]
