# Generated by Django 5.2.17 on 2026-10-02 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_upload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='просмотры (посты канала)'),
        ),
        migrations.AddField(
            model_name='thread',
            name='about',
            field=models.TextField(blank=True, max_length=500, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='thread',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='chat_avatars/', verbose_name='аватар'),
        ),
        migrations.AddField(
            model_name='thread',
            name='closed',
            field=models.BooleanField(default=False, help_text='Нельзя писать и вступать, пропадает из каталога', verbose_name='закрыт модератором'),
        ),
        migrations.AddField(
            model_name='thread',
            name='handle',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='публичное имя (адрес /c/имя/)'),
        ),
        migrations.AddField(
            model_name='thread',
            name='invite_code',
            field=models.CharField(blank=True, db_index=True, max_length=24, verbose_name='код приглашения'),
        ),
        migrations.AddField(
            model_name='thread',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Виден в каталоге, вступить может любой. Иначе — только по ссылке-приглашению', verbose_name='публичный'),
        ),
        migrations.AddField(
            model_name='thread',
            name='members_count',
            field=models.PositiveIntegerField(default=0, verbose_name='участников'),
        ),
        migrations.AddField(
            model_name='thread',
            name='only_admins_post',
            field=models.BooleanField(default=False, help_text='Для группы. В канале всегда пишут только владелец и админы', verbose_name='пишут только админы'),
        ),
        migrations.AddField(
            model_name='thread',
            name='platform_verified',
            field=models.BooleanField(default=False, help_text='Мечеть, учитель, организация — проверено командой ilm4', verbose_name='официальный (галочка ilm4)'),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Админ'), ('member', 'Участник'), ('banned', 'Удалён')], default='member', max_length=8, verbose_name='роль')),
                ('muted', models.BooleanField(default=False, verbose_name='без звука')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='прочитано до')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'участник группы / канала',
                'verbose_name_plural': 'участники групп и каналов',
                'indexes': [models.Index(fields=['user', 'thread'], name='chat_member_user_id_c0e85c_idx')],
                'constraints': [models.UniqueConstraint(fields=('thread', 'user'), name='one_membership')],
            },
        ),
    ]
