# Generated by Django 5.2.17 on 2026-10-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
            ],
            options={
                'verbose_name': 'группа / канал',
                'verbose_name_plural': 'группы и каналы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chat.thread',),
        ),
    ]
