# Generated by Django 5.2.17 on 2026-10-02 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_room_proxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='comment_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='chat.message', verbose_name='комментарий к посту'),
        ),
        migrations.AddField(
            model_name='message',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='комментариев'),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='изменено'),
        ),
        migrations.AddField(
            model_name='message',
            name='fwd_enc',
            field=models.TextField(blank=True, verbose_name='переслано от (зашифровано)'),
        ),
        migrations.AddField(
            model_name='message',
            name='pinned_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='закреплено'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message', verbose_name='ответ на'),
        ),
        migrations.AddField(
            model_name='thread',
            name='comments_on',
            field=models.BooleanField(default=False, verbose_name='комментарии к постам (канал)'),
        ),
        migrations.AddField(
            model_name='thread',
            name='protected',
            field=models.BooleanField(default=False, help_text='Как «Запретить копирование» в Telegram: сообщения нельзя переслать', verbose_name='запретить пересылку и копирование'),
        ),
        migrations.AddField(
            model_name='thread',
            name='reactions_on',
            field=models.BooleanField(default=True, verbose_name='реакции включены'),
        ),
        migrations.AddField(
            model_name='thread',
            name='slow_seconds',
            field=models.PositiveIntegerField(default=0, help_text='0 — выключен. Участник пишет не чаще, чем раз в N секунд', verbose_name='медленный режим, сек (группа)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('text', 'Текст'), ('photo', 'Фото'), ('video', 'Видео'), ('voice', 'Голосовое'), ('circle', 'Видеокружок'), ('file', 'Файл'), ('system', 'Служебное'), ('poll', 'Опрос')], default='text', max_length=8, verbose_name='вид'),
        ),
        migrations.CreateModel(
            name='ChatFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24, verbose_name='название')),
                ('emoji', models.CharField(blank=True, max_length=8, verbose_name='значок')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('types', models.JSONField(blank=True, default=list, verbose_name='типы чатов')),
                ('no_muted', models.BooleanField(default=False, verbose_name='без «без звука»')),
                ('no_read', models.BooleanField(default=False, verbose_name='без прочитанных')),
                ('no_archived', models.BooleanField(default=True, verbose_name='без архивных')),
                ('pins', models.JSONField(blank=True, default=list, verbose_name='закреплённые в папке (id чатов по порядку)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exclude', models.ManyToManyField(blank=True, related_name='+', to='chat.thread', verbose_name='всегда исключать')),
                ('include', models.ManyToManyField(blank=True, related_name='+', to='chat.thread', verbose_name='всегда включать')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'папка чатов',
                'verbose_name_plural': 'папки чатов',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ChatState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_at', models.DateTimeField(blank=True, null=True, verbose_name='закреплён в общем списке')),
                ('archived', models.BooleanField(default=False, verbose_name='в архиве')),
                ('unread_mark', models.BooleanField(default=False, verbose_name='помечен непрочитанным')),
                ('draft_enc', models.TextField(blank=True, verbose_name='черновик (зашифрован)')),
                ('cleared_at', models.DateTimeField(blank=True, null=True, verbose_name='история очищена до')),
                ('hidden', models.BooleanField(default=False, verbose_name='убран из списка (до нового сообщения)')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='chat.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'состояние чата',
                'verbose_name_plural': 'состояния чатов',
                'constraints': [models.UniqueConstraint(fields=('user', 'thread'), name='one_chat_state')],
            },
        ),
        migrations.CreateModel(
            name='HiddenMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_for', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'скрытое сообщение',
                'verbose_name_plural': 'скрытые сообщения',
                'constraints': [models.UniqueConstraint(fields=('user', 'message'), name='one_hidden')],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'реакция',
                'verbose_name_plural': 'реакции',
                'constraints': [models.UniqueConstraint(fields=('message', 'user'), name='one_reaction')],
            },
        ),
    ]
