# Generated by Django 5.2.17 on 2026-10-03 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_telegram_core'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='space_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='название')),
                ('about', models.CharField(blank=True, max_length=500, verbose_name='описание')),
                ('icon', models.ImageField(blank=True, upload_to='chat/spaces/', verbose_name='значок')),
                ('handle', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='адрес')),
                ('is_public', models.BooleanField(default=False, verbose_name='виден в каталоге, вступить может любой')),
                ('invite_code', models.CharField(max_length=24, unique=True)),
                ('members_count', models.PositiveIntegerField(default=0)),
                ('platform_verified', models.BooleanField(default=False, verbose_name='официальное (галочка ilm4)')),
                ('closed', models.BooleanField(default=False, verbose_name='закрыто модератором')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spaces_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'сообщество',
                'verbose_name_plural': 'сообщества',
            },
        ),
        migrations.AddField(
            model_name='thread',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='chat.space'),
        ),
        migrations.CreateModel(
            name='SpaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='chat.space')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='thread',
            name='space_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='chat.spacecategory'),
        ),
        migrations.CreateModel(
            name='SpaceVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voices', to='chat.spacecategory')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voices', to='chat.space')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SpaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Админ'), ('mod', 'Модератор'), ('member', 'Участник'), ('banned', 'Удалён')], default='member', max_length=8, verbose_name='роль')),
                ('nick', models.CharField(blank=True, max_length=32, verbose_name='ник в сообществе')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'участник сообщества',
                'verbose_name_plural': 'участники сообществ',
                'indexes': [models.Index(fields=['user', 'space'], name='chat_spacem_user_id_7b9d29_idx')],
                'constraints': [models.UniqueConstraint(fields=('space', 'user'), name='one_space_membership')],
            },
        ),
    ]
