# Generated by Django 5.2.17 on 2026-10-03 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_spaces'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spacemember',
            name='muted_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='тайм-аут до'),
        ),
        migrations.AddField(
            model_name='thread',
            name='space_private',
            field=models.BooleanField(default=False, verbose_name='закрытый канал сообщества (только выбранным ролям)'),
        ),
        migrations.AddField(
            model_name='thread',
            name='space_topic',
            field=models.CharField(blank=True, max_length=200, verbose_name='тема канала'),
        ),
        migrations.CreateModel(
            name='SpaceInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(default=0)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='chat.space')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='SpaceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=24)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='chat.space')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='SpaceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('color', models.CharField(default='#6d5efc', max_length=7)),
                ('perms', models.JSONField(blank=True, default=list)),
                ('hoist', models.BooleanField(default=True, verbose_name='показывать отдельной группой в списке участников')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('private_threads', models.ManyToManyField(blank=True, related_name='space_roles_allowed', to='chat.thread')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='chat.space')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='spacemember',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='holders', to='chat.spacerole'),
        ),
        migrations.CreateModel(
            name='SpaceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('todo', 'Идеи и задачи'), ('doing', 'Делаем'), ('done', 'Готово')], default='todo', max_length=6)),
                ('due', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='space_tasks', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='chat.space')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
